import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center">
          <div className="w-full flex justify-center items-center h-20 border-b-2 border-indigo-100">
            <div className="flex justify-between items-center w-3/5">
              <div className="font-bold font-sans text-2xl">Instagram</div>
              <div className="flex gap-4">
                <button className="bg-sky-500/100 text-white font-bold rounded-md px-4 py-2">
                  Log In
                </button>
                <button className="text-sky-500/100 font-bold  px-4 py-2">
                  Sign Up
                </button>
              </div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
